# Generated by Django 2.1.3 on 2018-11-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.FileField(max_length=250, null=True, upload_to='storage/images/')),
                ('detalles', models.TextField(null=True)),
                ('estado', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
